#!/usr/bin/env node
// ═══════════════════════════════════════════════════════════════════════
// remove-bg.mjs — batch background removal via fal.ai's Bria model
//
// Flux doesn't reliably honor "transparent background" in prompts, so
// the icons generated by gen-art.mjs end up with washed-out white or
// pale backgrounds instead of alpha. This script runs each image through
// fal-ai/bria/background-removal, which produces clean transparent PNGs.
//
// Usage:
//   node tools/remove-bg.mjs                                    # all icon-like assets in ui/
//   node tools/remove-bg.mjs --only=tab-home.png,icon-coin.png  # specific files
//   node tools/remove-bg.mjs --dir=src/assets/images/ui         # custom dir
//
// Cost: ~$0.01 per image on Bria.
// ═══════════════════════════════════════════════════════════════════════

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DEFAULT_DIR = path.join(ROOT, 'src', 'assets', 'images', 'ui');
const ENV_LOCAL = path.join(ROOT, '.env.local');

function loadEnvLocal() {
  if (!fs.existsSync(ENV_LOCAL)) return;
  const text = fs.readFileSync(ENV_LOCAL, 'utf-8');
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.+)$/);
    if (!m) continue;
    const [, k, rawV] = m;
    const v = rawV.trim().replace(/^["']|["']$/g, '');
    if (!(k in process.env)) process.env[k] = v;
  }
}
loadEnvLocal();

// Assets that should have transparent backgrounds (icons, particles).
// Backgrounds, mode cards, and stage art are supposed to fill their space,
// so they're excluded from the default sweep.
const DEFAULT_TARGETS = [
  // Tab icons
  'tab-home.png', 'tab-challenges.png', 'tab-collection.png', 'tab-profile.png', 'tab-shop.png',
  // Currency
  'icon-coin.png', 'icon-gem.png', 'icon-streak.png',
  // Shop tabs
  'shop-outfits.png', 'shop-boards.png', 'shop-pieces.png', 'shop-effects.png',
  'shop-wins.png', 'shop-frames.png', 'shop-emotes.png', 'shop-pets.png', 'shop-boxes.png',
  // Particles
  'particle-sparkle.png', 'particle-coin-burst.png', 'particle-win-trophy.png',
  // Frames (need transparency in the center)
  'frame-shop-card.png', 'frame-portrait-gold.png',
];

const args = new Set(process.argv.slice(2));
const onlyArg = [...args].find((a) => a.startsWith('--only='));
const dirArg = [...args].find((a) => a.startsWith('--dir='));
const DRY_RUN = args.has('--dry-run');
const TARGET_DIR = dirArg ? path.resolve(ROOT, dirArg.split('=')[1]) : DEFAULT_DIR;
const TARGETS = onlyArg
  ? onlyArg.split('=')[1].split(',').map((s) => s.trim())
  : DEFAULT_TARGETS;

async function stripBackground(buffer, apiKey) {
  // fal-ai/bria/background/remove takes a URL or data URL. We upload as
  // a data URL — API accepts up to ~10MB.
  const base64 = buffer.toString('base64');
  const dataUrl = `data:image/png;base64,${base64}`;
  const body = { image_url: dataUrl };

  const submitRes = await fetch('https://queue.fal.run/fal-ai/bria/background/remove', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Key ${apiKey}`,
    },
    body: JSON.stringify(body),
  });
  if (!submitRes.ok) {
    throw new Error(`bria submit ${submitRes.status}: ${(await submitRes.text()).slice(0, 200)}`);
  }
  const { status_url: statusUrl, response_url: responseUrl } = await submitRes.json();

  const startTime = Date.now();
  while (Date.now() - startTime < 60_000) {
    await new Promise((r) => setTimeout(r, 1000));
    const statusRes = await fetch(statusUrl, {
      headers: { 'Authorization': `Key ${apiKey}` },
    });
    if (!statusRes.ok) continue;
    const status = await statusRes.json();
    if (status.status === 'COMPLETED') break;
    if (status.status === 'FAILED') {
      throw new Error('bria job failed: ' + JSON.stringify(status).slice(0, 200));
    }
  }

  const resultRes = await fetch(responseUrl, {
    headers: { 'Authorization': `Key ${apiKey}` },
  });
  if (!resultRes.ok) throw new Error(`bria result ${resultRes.status}`);
  const result = await resultRes.json();
  const imageUrl = result?.image?.url;
  if (!imageUrl) throw new Error('bria result has no image URL');

  const imgRes = await fetch(imageUrl);
  if (!imgRes.ok) throw new Error(`bria image download ${imgRes.status}`);
  const arr = await imgRes.arrayBuffer();
  return Buffer.from(arr);
}

async function main() {
  const apiKey = process.env.FAL_KEY || process.env.FAL_API_KEY;
  if (!apiKey) {
    console.error('FAL_KEY missing (add to .env.local)');
    process.exit(1);
  }

  const files = TARGETS
    .map((f) => path.join(TARGET_DIR, f))
    .filter((p) => fs.existsSync(p));

  if (files.length === 0) {
    console.error(`No matching files in ${TARGET_DIR}`);
    process.exit(1);
  }

  console.log(`\nPlan: strip background from ${files.length} image${files.length === 1 ? '' : 's'}.`);
  console.log(`Estimated cost: $${(files.length * 0.01).toFixed(3)} at Bria rate.\n`);

  if (DRY_RUN) {
    for (const f of files) console.log(`  ${path.basename(f)}`);
    console.log('\n(dry run — no API calls)');
    return;
  }

  let ok = 0, fail = 0;
  for (const [i, f] of files.entries()) {
    const label = `[${i + 1}/${files.length}] ${path.basename(f)}`;
    process.stdout.write(`${label}  …`);
    try {
      const buffer = fs.readFileSync(f);
      const cleaned = await stripBackground(buffer, apiKey);
      fs.writeFileSync(f, cleaned);
      process.stdout.write(`\r${label}  ✓ ${cleaned.length.toLocaleString()} bytes\n`);
      ok += 1;
    } catch (err) {
      process.stdout.write(`\r${label}  ✗ ${err.message.slice(0, 150)}\n`);
      fail += 1;
    }
  }
  console.log(`\nDone. ${ok} ok, ${fail} failed.`);
  if (fail > 0) process.exit(2);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
